import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

// Get AI generations for a specific field
export const getGenerations = query({
  args: {
    resumeId: v.id("resumes"),
    fieldType: v.string(),
    fieldId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const generations = await ctx.db
      .query("aiGenerations")
      .withIndex("by_resume_field", (q) =>
        q
          .eq("resumeId", args.resumeId)
          .eq("fieldType", args.fieldType)
          .eq("fieldId", args.fieldId)
      )
      .first();

    return generations;
  },
});

// Check if auto-generation has happened for a field
export const hasAutoGenerated = query({
  args: {
    resumeId: v.id("resumes"),
    fieldType: v.string(),
    fieldId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const record = await ctx.db
      .query("aiGenerations")
      .withIndex("by_resume_field", (q) =>
        q
          .eq("resumeId", args.resumeId)
          .eq("fieldType", args.fieldType)
          .eq("fieldId", args.fieldId)
      )
      .first();

    return record?.hasAutoGenerated ?? false;
  },
});

// Save a new AI generation
export const saveGeneration = mutation({
  args: {
    resumeId: v.id("resumes"),
    fieldType: v.string(),
    fieldId: v.optional(v.string()),
    originalContent: v.string(),
    generatedContent: v.string(),
    tone: v.string(),
    prompt: v.optional(v.string()),
    isAutoGenerated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();

    // Check if a record already exists for this field
    const existing = await ctx.db
      .query("aiGenerations")
      .withIndex("by_resume_field", (q) =>
        q
          .eq("resumeId", args.resumeId)
          .eq("fieldType", args.fieldType)
          .eq("fieldId", args.fieldId)
      )
      .first();

    const newGeneration = {
      content: args.generatedContent,
      tone: args.tone,
      prompt: args.prompt,
      createdAt: now,
    };

    if (existing) {
      // Append to existing generations array
      await ctx.db.patch(existing._id, {
        generations: [...existing.generations, newGeneration],
        originalContent: args.originalContent, // Update original content
        hasAutoGenerated: existing.hasAutoGenerated || args.isAutoGenerated || false,
        updatedAt: now,
      });
      return existing._id;
    } else {
      // Create new record
      const id = await ctx.db.insert("aiGenerations", {
        resumeId: args.resumeId,
        fieldType: args.fieldType,
        fieldId: args.fieldId,
        originalContent: args.originalContent,
        generations: [newGeneration],
        hasAutoGenerated: args.isAutoGenerated || false,
        createdAt: now,
        updatedAt: now,
      });
      return id;
    }
  },
});

// Mark a field as having been auto-generated
export const markAutoGenerated = mutation({
  args: {
    resumeId: v.id("resumes"),
    fieldType: v.string(),
    fieldId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("aiGenerations")
      .withIndex("by_resume_field", (q) =>
        q
          .eq("resumeId", args.resumeId)
          .eq("fieldType", args.fieldType)
          .eq("fieldId", args.fieldId)
      )
      .first();

    if (existing) {
      await ctx.db.patch(existing._id, {
        hasAutoGenerated: true,
        updatedAt: Date.now(),
      });
    }
  },
});

// Clear generations for a field (when content changes significantly)
export const clearGenerations = mutation({
  args: {
    resumeId: v.id("resumes"),
    fieldType: v.string(),
    fieldId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("aiGenerations")
      .withIndex("by_resume_field", (q) =>
        q
          .eq("resumeId", args.resumeId)
          .eq("fieldType", args.fieldType)
          .eq("fieldId", args.fieldId)
      )
      .first();

    if (existing) {
      await ctx.db.delete(existing._id);
    }
  },
});
